# Generated by Django 3.1 on 2021-02-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/profile', verbose_name='تصویر'),
        ),
    ]
