# Generated by Django 3.1 on 2021-02-12 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='a', max_length=100)),
                ('file', models.FileField(upload_to='music/self.artist')),
                ('image', models.ImageField(upload_to='images/covers')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ManyToManyField(null=True, to='artist.Artist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'موزیک',
                'verbose_name_plural': 'موزیک ها',
                'ordering': ('upload_date',),
            },
        ),
    ]
