# Generated by Django 3.1 on 2021-02-12 19:43

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_artist_position'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(to='artist.Artist'),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(upload_to='music/tracks', validators=[music.models.validate_file_extension]),
        ),
    ]
