# Generated by Django 3.1 on 2021-02-14 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0003_auto_20210214_0546'),
        ('music', '0002_auto_20210212_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ('-upload_date',), 'verbose_name': 'موزیک', 'verbose_name_plural': 'موزیک ها'},
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(to='artist.Artist', verbose_name='خواننده'),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(upload_to='music/tracks', validators=[music.models.validate_file_extension], verbose_name='فایل آهنگ'),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(default='images/covers/default.jpg', upload_to='images/covers', verbose_name='کاور'),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام آهنگ'),
        ),
        migrations.AlterField(
            model_name='music',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه کردن'),
        ),
        migrations.AlterField(
            model_name='music',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
