# Generated by Django 3.1 on 2021-02-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/artists')),
                ('position', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'هنرمند',
                'verbose_name_plural': 'هنرمند ها',
                'ordering': ['name'],
            },
        ),
    ]
