# Generated by Django 3.1 on 2021-02-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='position',
        ),
    ]
