# Generated by Django 3.1 on 2021-02-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_artist_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(upload_to='images/artists', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام خواننده'),
        ),
    ]
